openapi: 3.0.3

info:
  title: Auth Service API
  description: Auth Service API
  version: 1.0.0

servers:
  - url: 'http://localhost:8080/api'
    description: 'Local Server'

paths:
  /auth/register:
    post:
      summary: Register a new user
      operationId: register
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/CommonResponse'
                  - type: object
                    properties:
                      message:
                        type: string
                        description: Custom success message
                        example: "Registration successful"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500InternalError'
  /auth/login:
    post:
      summary: Login a user
      operationId: login
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/RefreshTokenResponse'
                  - type: object
                    properties:
                      message:
                        type: string
                        description: Custom success message
                        example: "Login successful"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500InternalError'
  /auth/login-oauth:
    post:
      summary: Login a user using OAuth
      operationId: loginOAuth
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuthLoginRequest'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/CommonResponse'
                  - type: object
                    properties:
                      message:
                        type: string
                        description: Custom success message
                        example: "Login successful"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500InternalError'
  /auth/verify-email:
    post:
      summary: Verify email
      operationId: verifyEmail
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyEmailRequest'
      responses:
        '200':
          description: Email verified successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyEmailResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500InternalError'
  /auth/resend-verification-email:
    post:
        summary: Resend email verification code
        operationId: resendVerificationEmail
        tags:
            - auth
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResendVerificationEmailRequest'
        responses:
            '200':
              description: Email verification code sent successfully
              content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/CommonResponse'
            '400':
              description: Bad Request
              content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/CommonErrorResponse'
            '500':
              description: Internal Server Error
              content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/500InternalError'
  /auth/forgot-password:
    post:
      summary: Forgot password
      operationId: forgotPassword
      tags:
        - auth
      responses:
        '200':
          description: Password reset link sent successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/CommonResponse'
                  - type: object
                    properties:
                      message:
                        type: string
                        description: Custom success message
                        example: "Verification code sent to email"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500InternalError'
  /auth/reset-password:
    post:
      summary: Reset password
      operationId: resetPassword
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '200':
          description: Password reset successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/CommonResponse'
                  - type: object
                    properties:
                      message:
                        type: string
                        description: Custom success message
                        example: "Password reset successfully"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500InternalError'
  /auth/refresh-token:
    post:
      summary: Refresh token
      operationId: refreshToken
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  description: Refresh token
                  example: "eyJhbGciO"
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshTokenResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500InternalError'

components:
  schemas:
    CommonResponse:
      type: object
      properties:
        message:
          type: string
          description: Response message
          example: "Operation successful"
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          description: User email
          example: "john.doe@example.com"
        password:
          type: string
          description: User password
          example: "password"
        username:
          type: string
          description: User username
          example: "johndoe"
        displayName:
          type: string
          description: User display name
          example: "John Doe"
    500InternalError:
      type: object
      description: Internal Server Error Occurred
      properties:
        errorCode:
          type: string
          description: internalServerErrorOccurred
          example: ERROR1
        message:
          type: string
          description: Internal Server Error has Occurred
          example: Internal Server Error has Occurred
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          description: User email
          example: "john.doe@gmajl.com"
        password:
          type: string
          description: User password
          example: "password"
        ipAddress:
          type: string
          description: User IP address
          example: "123.123.123.123"
        userAgent:
          type: string
          description: User agent
          example: "Mozilla/5.0"
    OAuthLoginRequest:
      type: object
      properties:
        authorizationCode:
          type: string
          description: Authorization code from OAuth provider
          example: "authorizationCode"
    VerifyEmailRequest:
      type: object
      properties:
        type:
          type: string
          description: Type of verify email request
          example: "ACCOUNT_REGISTRATION"
        email:
          type: string
          description: User email
          example: "johndoe@example.com"
        verificationCode:
          type: string
          description: "Verification code sent to the user's email"
          example: "212038"
    VerifyEmailResponse:
      type: object
      properties:
        type:
          type: string
          description: Type of email verification
          example: "ACCOUNT_REGISTRATION"
        message:
          type: string
          description: Response message
          example: "Email verified successfully"
        tokens:
          type: object
          description: Tokens that can be used for later usage
    ResetPasswordRequest:
      type: object
      properties:
        email:
          type: string
          description: User email
          example: "john.doe@gmail.com"
        oldPassword:
          type: string
          description: User old password
          example: "oldPassword"
        newPassword:
          type: string
          description: User new password
          example: "newPassword"
    ResendVerificationEmailRequest:
      type: object
      properties:
          type:
            type: string
            description: Type of email verification
            example: "ACCOUNT_REGISTRATION"
          email:
            type: string
            description: User email
            example: "johndoe@example.com"
    ResendVerificationEmailSuccessfulResponse:
      type: object
      properties:
        message:
          type: string
          description: Response message
          example: "Email verification code sent successfully"
        retryAfterSeconds:
            type: integer
            description: Retry after seconds
            example: 120
    CommonErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          description: Code of the error
          example: "USER12"
        message:
          type: string
          description: Response message
          example: "Operation Failed"

    RefreshTokenResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: New access token
          example: "eyJhbGciO"
        refreshToken:
          type: string
          description: New refresh token
          example: "eyJhbGciO"