jwt:
  expiration-time-access-token: 30
  expiration-time-refresh-token: 12
  limit-refresh-token-usage-consecutive-minutes: 5
  secret-key: 462D4A614E645267556B58703272357538782F413F4428472B4B625065536856
mail:
  from: mail@gmail.com
  path:
    register-verification-mail: classpath:/mail/verification-mail.html
server:
  port: 8081
spring:
  application:
    name: auth-service
  cloud:
    function:
      definition: userRegistrationDownstream
    stream:
      bindings:
        userRegistrationDownstream-out-0:
          destination: topic.user.registration
      kafka:
        binder:
          brokers: localhost:9092
  flyway:
    baselineOnMigrate: true
    enabled: true
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/auth_service
    user: ${spring.r2dbc.username}
    validateOnMigrate: false
  mail:
    host: smtp.gmail.com
    username: alexdevo300031@gmail.com
    password: fukzxprulhgrwtbi
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: dev
  r2dbc:
    password: postgres
    url: r2dbc:postgresql://localhost:5432/auth_service
    username: postgres
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
media-service:
  url: http://media-service/api/media/image